local BANKER_CHANNEL = 1
local TELLER_CHANNEL = 2
local PRICER_CHANNEL = 3
local STOCKER_CHANNEL = 4
local REPLICATER_CHANNEL = 5

return {
  BANKER_CHANNEL = BANKER_CHANNEL,
  TELLER_CHANNEL = TELLER_CHANNEL,
  PRICER_CHANNEL = PRICER_CHANNEL,
  STOCKER_CHANNEL = STOCKER_CHANNEL,
  REPLICATER_CHANNEL = REPLICATER_CHANNEL
}
