local BANKER_CHANNEL = 1
local TELLER_CHANNEL = 2
local PRICER_CHANNEL = 3
local STOCKER_CHANNEL = 4
local REPLICATER_CHANNEL = 5
local REPLICATER_TURTLE_CHANNEL = 6

return {
  BANKER_CHANNEL = BANKER_CHANNEL,
  TELLER_CHANNEL = TELLER_CHANNEL,
  PRICER_CHANNEL = PRICER_CHANNEL,
  STOCKER_CHANNEL = STOCKER_CHANNEL,
  REPLICATER_CHANNEL = REPLICATER_CHANNEL,
  REPLICATER_TURTLE_CHANNEL = REPLICATER_TURTLE_CHANNEL,
}
